## LSTM RNN TRAINING 


DATA IMPORTING 

In [24]:
import pandas as pd 
import numpy as np 
import pathlib as path
with open(r"D:\rnn\next_word_predictor.txt", mode='r') as file :
    text = file.read().lower()
text

'the sun was shining brightly in the clear blue sky, and a gentle breeze rustled the leaves of the tall trees. people were out enjoying the beautiful weather, some sitting in the park, others taking a leisurely stroll along the riverbank. children were playing games, and laughter filled the air.\n\nas the day turned into evening, the temperature started to drop, and the sky transformed into a canvas of vibrant colors. families gathered for picnics, and the smell of barbecues wafted through the air. it was a perfect day for a picnic by the lake.\n\nin the distance, you could hear the sound of live music coming from a local band, and people began to gather around the stage to enjoy the performance. the atmosphere was electric, and the music had everyone swaying to the beat.\n\nas the stars began to twinkle in the night sky, the crowd grew even larger, and the festivities continued well into the night. it was a day filled with joy, laughter, and memories that would last a lifetime.\n\n\nt

# WORD EMBBENDING

 sentance to words 

In [25]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
 
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1
total_words



4994

In [26]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'a': 3,
 'of': 4,
 'to': 5,
 'i': 6,
 'you': 7,
 'in': 8,
 'is': 9,
 'monica': 10,
 'it': 11,
 'with': 12,
 'ross': 13,
 'that': 14,
 'rachel': 15,
 'for': 16,
 'chandler': 17,
 'this': 18,
 'on': 19,
 'joey': 20,
 'was': 21,
 'oh': 22,
 'phoebe': 23,
 'are': 24,
 'all': 25,
 'as': 26,
 'what': 27,
 'be': 28,
 'like': 29,
 'no': 30,
 "it's": 31,
 "i'm": 32,
 'her': 33,
 'they': 34,
 'just': 35,
 'from': 36,
 'okay': 37,
 'not': 38,
 'so': 39,
 'my': 40,
 'have': 41,
 'me': 42,
 'where': 43,
 'know': 44,
 'she': 45,
 'we': 46,
 'out': 47,
 'well': 48,
 'their': 49,
 'can': 50,
 'at': 51,
 'he': 52,
 'yeah': 53,
 'your': 54,
 'about': 55,
 'but': 56,
 'its': 57,
 'up': 58,
 "don't": 59,
 'text': 60,
 'scene': 61,
 'by': 62,
 'do': 63,
 'an': 64,
 'or': 65,
 'were': 66,
 'there': 67,
 'if': 68,
 'uh': 69,
 'look': 70,
 'life': 71,
 'through': 72,
 'into': 73,
 'him': 74,
 'his': 75,
 "you're": 76,
 'hey': 77,
 'how': 78,
 'right': 79,
 'think': 80,
 'time': 81,
 'no

padding and input swquence 


In [27]:
input_seq=[]

for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range (1,len(token_list)):
        seq=token_list[:i+1]
        input_seq.append(seq)






        

In [28]:
input_seq

[[1, 155],
 [1, 155, 21],
 [1, 155, 21, 2368],
 [1, 155, 21, 2368, 1549],
 [1, 155, 21, 2368, 1549, 8],
 [1, 155, 21, 2368, 1549, 8, 1],
 [1, 155, 21, 2368, 1549, 8, 1, 422],
 [1, 155, 21, 2368, 1549, 8, 1, 422, 692],
 [1, 155, 21, 2368, 1549, 8, 1, 422, 692, 215],
 [1, 155, 21, 2368, 1549, 8, 1, 422, 692, 215, 2],
 [1, 155, 21, 2368, 1549, 8, 1, 422, 692, 215, 2, 3],
 [1, 155, 21, 2368, 1549, 8, 1, 422, 692, 215, 2, 3, 2369],
 [1, 155, 21, 2368, 1549, 8, 1, 422, 692, 215, 2, 3, 2369, 1550],
 [1, 155, 21, 2368, 1549, 8, 1, 422, 692, 215, 2, 3, 2369, 1550, 2370],
 [1, 155, 21, 2368, 1549, 8, 1, 422, 692, 215, 2, 3, 2369, 1550, 2370, 1],
 [1, 155, 21, 2368, 1549, 8, 1, 422, 692, 215, 2, 3, 2369, 1550, 2370, 1, 423],
 [1,
  155,
  21,
  2368,
  1549,
  8,
  1,
  422,
  692,
  215,
  2,
  3,
  2369,
  1550,
  2370,
  1,
  423,
  4],
 [1,
  155,
  21,
  2368,
  1549,
  8,
  1,
  422,
  692,
  215,
  2,
  3,
  2369,
  1550,
  2370,
  1,
  423,
  4,
  1],
 [1,
  155,
  21,
  2368,
  1549,
  8

max length in the seq 

In [29]:
max_seq_len=max ([len(x) for x in input_seq])
max_seq_len

325

In [30]:
input_equal=np.array(pad_sequences(input_seq,maxlen=max_seq_len,padding='pre'))
input_equal


array([[   0,    0,    0, ...,    0,    1,  155],
       [   0,    0,    0, ...,    1,  155,   21],
       [   0,    0,    0, ...,  155,   21, 2368],
       ...,
       [   0,    0,    0, ..., 2331,  290,   19],
       [   0,    0,    0, ...,  290,   19,   54],
       [   0,    0,    0, ...,   19,   54, 1535]])

now labbling and the pridectors 


In [31]:
import tensorflow as tf 

x,y=input_equal[:,:-1],input_equal[:,-1]



In [32]:
x

array([[   0,    0,    0, ...,    0,    0,    1],
       [   0,    0,    0, ...,    0,    1,  155],
       [   0,    0,    0, ...,    1,  155,   21],
       ...,
       [   0,    0,    0, ...,   64, 2331,  290],
       [   0,    0,    0, ..., 2331,  290,   19],
       [   0,    0,    0, ...,  290,   19,   54]])

In [33]:
y

array([ 155,   21, 2368, ...,   19,   54, 1535])

In [34]:
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

spliting data

In [35]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [36]:
# early stop when the best accuracy gained 

from tensorflow.keras.callbacks import EarlyStopping

earlystopping=EarlyStopping(monitor='val_loss',patience=3,restore_best_weights=True)




model building 

In [37]:
# model 
from tensorflow.keras.models import  Sequential
from tensorflow.keras.layers import Embedding ,LSTM,Dropout ,GRU,Dense

model = Sequential()
model.add(Embedding(total_words,100,input_length=max_seq_len-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation="softmax"))


In [45]:
# compileation 
model.compile(
    loss="categorical_crossentropy", 
    optimizer="adam", 
    metrics=["accuracy"]
)
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 324, 100)          499400    
                                                                 
 lstm_6 (LSTM)               (None, 324, 150)          150600    
                                                                 
 dropout_3 (Dropout)         (None, 324, 150)          0         
                                                                 
 lstm_7 (LSTM)               (None, 100)               100400    
                                                                 
 dense_1 (Dense)             (None, 4994)              504394    
                                                                 
Total params: 1254794 (4.79 MB)
Trainable params: 1254794 (4.79 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [46]:
## Train the model
history=model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test),verbose=1,callbacks=[earlystopping])


Epoch 1/50
660/660 [==============================] - 122s 182ms/step - loss: 7.1720 - accuracy: 0.0502 - val_loss: 6.9659 - val_accuracy: 0.0523
Epoch 2/50
660/660 [==============================] - 123s 186ms/step - loss: 6.6657 - accuracy: 0.0600 - val_loss: 6.8971 - val_accuracy: 0.0637
Epoch 3/50
660/660 [==============================] - 123s 187ms/step - loss: 6.4016 - accuracy: 0.0699 - val_loss: 6.8271 - val_accuracy: 0.0724
Epoch 4/50
660/660 [==============================] - 126s 190ms/step - loss: 6.1579 - accuracy: 0.0829 - val_loss: 6.7666 - val_accuracy: 0.0826
Epoch 5/50
660/660 [==============================] - 128s 195ms/step - loss: 5.9261 - accuracy: 0.0939 - val_loss: 6.7744 - val_accuracy: 0.0902
Epoch 6/50
660/660 [==============================] - 136s 207ms/step - loss: 5.7219 - accuracy: 0.1015 - val_loss: 6.7743 - val_accuracy: 0.0917
Epoch 7/50
660/660 [==============================] - 142s 216ms/step - loss: 5.5284 - accuracy: 0.1100 - val_loss: 6.8285 -

In [47]:
# Function to predict the next word
def predict_next_word(model, tokenizer, text, max_seq_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_seq_len:
        token_list = token_list[-(max_seq_len-1):]  # Ensure the sequence length matches max_sequence_len-1
    token_list = pad_sequences([token_list], maxlen=max_seq_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None

In [56]:
input_text=" a vast moat surrounded"
print(f"Input text:{input_text}")
max_seq_len=model.input_shape[1]+1
next_word=predict_next_word(model,tokenizer,input_text,max_seq_len)
print(f"Next Word PRediction:{next_word}")

Input text: a vast moat surrounded
Next Word PRediction:the


In [57]:
## Save the model
model.save("next_words_lstm.h5")
## Save the tokenizer
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)

d:\rnn\packeg_en\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
